### ISSUE TITLE
No way to create Energetic Alloy

### ISSUE THREAD

**Issue by VintageGnu** [TheLimePixel/Equivalent-Skies#1]
Pack Version: 1.2.1 (using the zip download with MultiMC)

JEI shows that Energetic Alloy can be created in either the Immersive Engineering Arc Furnace or the EnderIO Alloy Smelter.

Unfortunately the Arc Furnace requires pistons for the heavy engineering blocks, and pistons require EnderIO redstone alloy, which can only be created in an Alloy Smelter.

The Alloy Smelter requires a machine chassis, however this requires the Compact Machines crafting, but the Miniaturization Field Projectors require Energetic Alloy so you are stuck.

**Comment by SirioIlBe** [comment]
before you were able to make it in the smeltery from tinkers

**Comment by TheLimePixel** [comment]
Wait... strange, what could have possibly broken that recipe? 🤔 Guess it was changing the melting time.
