### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by MySickBananas** [TheLimePixel/Equivalent-Skies#11]
Through Botania you are not able to create the Orechid through the Petal Apothecary.

Also there is no recipe or way to get Industrial Hemp Seeds you cannot grow the fiber.

**Comment by efinder2** [comment]
@MySickBananas You can get the Hemp Seed. The recipe is not shown in JEI. You have to destroy (much) Grass (not the blocks). You also don't see the recipe for vanilla seeds...
I think the Orechid is disabled. You are able to create great amounts of EMC.

**Comment by MySickBananas** [comment]
Thank You, but is the only way to receive quicksilver from breaking the silverwood trees? Because the only other way to get cinnabar is to use the Orechid unless i'm missing something.

**Comment by TheLimePixel** [comment]
Yes
