### ISSUE TITLE
Integrated Dynamics machines don't work after update

### ISSUE THREAD

**Issue by SirioIlBe** [TheLimePixel/Equivalent-Skies#2]
Packe version 1.2.2

after this update my squeezer,generator and mechanical drying basin from integrated dynamics stopped working. i put fuel in the generator and it cosumes it but the machines don't get any power

**Comment by TheLimePixel** [comment]
Also, it's only the Generator that doesn't work. The rest just have broken progress and energy bars.

**Comment by SirioIlBe** [comment]
yes,i saw that...i used the coal generator and the machines work
