### ISSUE TITLE
Items randomly disappearing from certain inventories

### ISSUE THREAD

**Issue by Alexejhero** [TheLimePixel/Equivalent-Skies#8]
I'm having an issue where some items randomly disappear and appear again from certain inventories like the Research table. This issue is prevent me from progressing. 
I am on a server, on which I play alone. I'm using the latest version

https://www.youtube.com/watch?v=fMznDcSRgZ4

**Comment by Alexejhero** [comment]
Also happens for Coke Oven, but not for Blast Furnace

**Comment by CyberGuy678** [comment]
All of my stuff disappeared from my inventory when I joined my world for a second time
I play singleplayer
